# Create a secret for the local cluster, to use as it as ApplicationSet cluster generator
apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: local-cluster
  labels:
    # Secret to add resources to this cluster
    argocd.argoproj.io/secret-type: cluster
    environment: "dev"
    provider: "local"
    non-prod: "true"
type: Opaque
stringData:
  name: local-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }

