apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: staging-digitalocean-ams3-1
  labels:
  # Secret to add resources to this cluster
    argocd.argoproj.io/secret-type: cluster
    environment: "staging"
    provider: "digitalocean"
type: Opaque
stringData:
  # All configuration to be able to connect to the remote cluster. In this case, the remote cluster lives in Digital Ocean cloud provider
  name: staging-digitalocean-ams3-1
  server: https://c50189b1-bb18-4a46-b772-b045e0ed4fde.k8s.ondigitalocean.com
  config: |
    {
      "bearerToken": "###", # dont push secrets into git NOTE:  use sealed secrets as a solution for secrets in gitops.
      "tlsClientConfig": {
        "insecure": false,
        "caData": "###"
      }
    }
