apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: diffing-customization-demo
  namespace: argocd
spec: 
  destination:
    namespace: diffing-customization-demo
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/dancer1325/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  # Ignore diffing customization
  ignoreDifferences:
    - group: apps
      kind: Deployment
      # based on jsonPointers (=== relative references to attributes in a JSON)
      jsonPointers:
      - /spec/replicas


    
