apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-app
  namespace: argocd
spec: 
  destination: 
    namespace: helm-app
    server: "https://kubernetes.default.svc"
  project: default
  source:
    # specify via git repo
    path: helm-guestbook    # Relative path to the repoURL
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
    helm:
     releaseName: my-release    # modify releaseName that by default would be the metadata.name
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    
