apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Dev Project
  sourceRepos:
  - '*'

  # https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L558
  destinations:
  - namespace: ns-1
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
