apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-2
  # Deploy the ApplicationSet in the ArgoCD's namespaced
  namespace: argocd
spec:
  generators:
  # ApplicationSet via Cluster generator
  - clusters:
     selector:
       # Based on the list of existing generators within ArgoCD --> filter via labels
       matchLabels:
        non-prod: "true"

  template:
    metadata:
      name: '{{name}}-guestbook-2'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/dancer1325/argocd-example-apps.git
        targetRevision: master
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: guestbook-2
      syncPolicy:
         syncOptions:
          - CreateNamespace=true