apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  # Deploy the ApplicationSet in the ArgoCD's namespace
  namespace: argocd
spec:
  generators:
  # ApplicationSet via List generator
  - list:
      elements:
      - cluster: local-dev                  # Cluster's name
        url: https://kubernetes.default.svc
      - cluster: staging-digitalocean       # Cluster's name
        # Based on the url, we know that it's a remote cluster
        url: https://c50189b1-bb18-4a46-b772-b045e0ed4fde.k8s.ondigitalocean.com
  template:
    metadata:
      # Cluster's parameters defined
      name: '{{cluster}}-guestbook'
      # Deploy the ApplicationSet's applications generated, in the ArgoCD's namespace
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/dancer1325/argocd-example-apps.git
        targetRevision: master
        path: guestbook
      destination:
        # Cluster's parameters defined
        server: '{{url}}'
        namespace: guestbook
      syncPolicy:
         syncOptions:
          - CreateNamespace=true